# PyTorch Tensor Basic Usage

- Create Tensor
- indexing, Joining, Slicing
- Initialization
- Math Operations

In [2]:
# 1. Create Tensor
# 1) random numbers
import torch

# torch.rand(sizes) --> (0,1) 사이의 실수형 값을 랜덤값으로 발생함
# sizes : 1차원 갯수, 2차원 행렬갯수 등 지정
# 0과 1사이의 실수형 숫자를 균등하게 생성
x = torch.rand(2, 3)
x

tensor([[0.6341, 0.4345, 0.8984],
        [0.2206, 0.8919, 0.1821]])

In [3]:
# torch.randn(sizes) --> Z(0,1)
# 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해서 생성 # numpy의 randn하고는 차이가 있다.
x = torch.randn(2,3)
x

tensor([[ 0.6051, -0.1206,  0.0131],
        [ 0.6021, -1.5659, -2.1001]])

In [4]:
# torch.randperm(n) --> permutation of 0 ~ n
x = torch.randperm(5)
x

tensor([4, 1, 0, 3, 2])

# **torch 에서 랜덤값으로 텐서 생성 **
1. torch.rand() : 0과 1사이의 숫자를 균등하게 생성
2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의
3. torch.randn() : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해서 생성
4. torch.randn_like() : 기존의 텐서를 사용해서 같은 텐서를 생성
5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성
6. torch.randint_like() : 텐서 이용, 같은 텐서 생성
7. torch.randperm() : 주어진 범위 내의 정수를 랜덤하게 생성