# PyTorch Tensor Basic Usage

- Create Tensor
- indexing, Joining, Slicing
- Initialization
- Math Operations

In [1]:
# 1. Create Tensor
# 1) random numbers
import torch

# torch.rand(sizes) --> (0,1) 사이의 실수형 값을 랜덤값으로 발생함
# sizes : 1차원 갯수, 2차원 행렬갯수 등 지정
# 0과 1사이의 실수형 숫자를 균등하게 생성
x = torch.rand(2, 3)
x

tensor([[0.1610, 0.3132, 0.4116],
        [0.9738, 0.5551, 0.7632]])

In [ ]:
# torch.randn(sizes) --> Z(0,1)
# 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해서 생성 # numpy의 randn하고는 차이가 있다.
x = torch.randn(2,3)
x

tensor([[ 0.6051, -0.1206,  0.0131],
        [ 0.6021, -1.5659, -2.1001]])

In [ ]:
# torch.randperm(n) --> permutation of 0 ~ n
x = torch.randperm(5)
x

tensor([4, 1, 0, 3, 2])

# **torch 에서 랜덤값으로 텐서 생성 **
1. torch.rand() : 0과 1사이의 숫자를 균등하게 생성
2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의
3. torch.randn() : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해서 생성
4. torch.randn_like() : 기존의 텐서를 사용해서 같은 텐서를 생성
5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성
6. torch.randint_like() : 텐서 이용, 같은 텐서 생성
7. torch.randperm() : 주어진 범위 내의 정수를 랜덤하게 생성

# 2) zeors, ones

In [2]:
# torch.zeros(2,3) ---> [[0,0,0], ..... [0,0,0]]
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [3]:
# torch.ones(2,3) --> [[1,1,1], .....[1,1,1]]
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
# torch.arange(start, end, step=1)
x = torch.arange(0, 3, step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

# **3) Tensor Data Type**

In [6]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2, 3)
x

tensor([[-1.2308e+30,  4.4044e-41,  3.7870e+33],
        [ 3.1692e-41,  4.4842e-44,  0.0000e+00]])

In [7]:
x = torch.FloatTensor([12,35])
x

tensor([12., 35.])

In [8]:
# tensor.type_as(tensor_type)
# 기존 텐서의 값의 자료형을 바꿀 때 사용
x = x.type_as(torch.IntTensor())
x

tensor([12, 35], dtype=torch.int32)

# **4) Numpy to Tensor, Tensor to Numpy**

In [14]:
import numpy as np

# torch.from_numpy(ndarray) --> Tensor
x1 = np.ndarray(shape=(2,3), dtype=int, buffer=np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)
x1,x2


(array([[1, 2, 3],
        [4, 5, 6]]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [15]:
# torch.numpy() --> ndarray
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

# **5) Tensor on CPU & GPU**

In [16]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [17]:
x_gpu = x.cuda()
x_gpu

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

# **6) Tensor size**

In [25]:
# tensor.size()  --> 인덱스값이
x = torch.FloatTensor(10, 12, 3, 3)
x.size()

torch.Size([10, 12, 3, 3])

# **2. Indexing, Slicing, Joining**

*1)Indexing*

In [26]:
# torch.index_select(input, dim, index)
x = torch.rand(4,3)
out = torch.index_select(x, 0, torch.LongTensor([0,3]))

x, out

(tensor([[0.7189, 0.7412, 0.8012],
         [0.3285, 0.3271, 0.8779],
         [0.4381, 0.0894, 0.8089],
         [0.8794, 0.2503, 0.9712]]),
 tensor([[0.7189, 0.7412, 0.8012],
         [0.8794, 0.2503, 0.9712]]))

In [27]:
# python indexing 사용 가능
x[:, 0], x[0, :], x[0:2, 0:2]

(tensor([0.7189, 0.3285, 0.4381, 0.8794]),
 tensor([0.7189, 0.7412, 0.8012]),
 tensor([[0.7189, 0.7412],
         [0.3285, 0.3271]]))

In [34]:
# torch.masked_select(input, mask)
x = torch.randn(2,3)
mask = torch.BoolTensor([[0,0,1],[0, 1, 0]])
out = torch.masked_select(x,mask)
out

tensor([-0.9219,  1.6499])

# **2) Joining**

In [42]:
# torch.cat(seq, dim=0)
x = torch.FloatTensor([[1,2,3], [4,5,6]])
y = torch.FloatTensor([[-1,-2,-3], [-4,-5,-6]])

z1 = torch.cat([x, y], dim=0)  # dim=0 (행), 아래에 합쳐짐
z2 = torch.cat([x, y], dim=1)  # dim=1 (열), 옆에 합쳐짐
x,y,z1,z2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [45]:
# torch.stack(sequence, dim=0) --> 새로운 차원으로 추가
x = torch.FloatTensor([[1,2,3], [4,5,6]]) # (2,3) shape 2행 3열 2차원
x_stack = torch.stack([x, x, x, x], dim=0) # (4, 2, 3)  4면 2행 3열 3차원
x, x_stack

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[[1., 2., 3.],
          [4., 5., 6.]],
 
         [[1., 2., 3.],
          [4., 5., 6.]],
 
         [[1., 2., 3.],
          [4., 5., 6.]],
 
         [[1., 2., 3.],
          [4., 5., 6.]]]))

# **3) Slicing**

In [49]:
# torch.chunk(tensor, chunks, dim=0)
x_1, x_2 = torch.chunk(z1, 2, dim =0) # dim=0이면 행을 2개로 분할 (여기서 2 는 chuck갯수)
x_1, x_2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]))

In [50]:
y_1, y_2, y_3 = torch.chunk(z1, 3, dim =1) # dim =1 이면 열을 3개로 분할
y_1, y_2, y_3

(tensor([[ 1.],
         [ 4.],
         [-1.],
         [-4.]]),
 tensor([[ 2.],
         [ 5.],
         [-2.],
         [-5.]]),
 tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

In [52]:
# torch.split(tensor, split_size, dim=0)
x1, x2 = torch.split(z1, 2, dim=0)
y1 = torch.split(z1, 2, dim=1) # 3개 열을 2개로 분리한 경우

z1, x1, x2,y1

(tensor([[ 1.,  2.],
         [ 4.,  5.],
         [-1., -2.],
         [-4., -5.]]),
 tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

# **4) squeezing**

In [53]:
# torch.squeeze(input, dim=None) #숫자가 1인 차원을 제거
x1 = torch.FloatTensor(10, 1, 3, 14)
# 차원(dimension) 의 개념
# 10 : batch size (데이터 한 묶음당 들어있는 데이터(x,y)쌍의 갯수)
# 1 : channel size
# 3 : with image size
# 14 : height image size

x2 = torch.squeeze(x1)

x1.size(), x2.size()

(torch.Size([10, 1, 3, 14]), torch.Size([10, 3, 14]))

In [55]:
# torch.unsqueeze(input, dim=None) ---> 숫자 1을 추가
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.unsqueeze(x1, dim=0) # dim=0 이면 첫번째 위치에 추가

x1.size(), x2.size()

(torch.Size([10, 3, 4]), torch.Size([1, 10, 3, 4]))

# **3. Initialization**

In [56]:
import torch.nn.init as init

In [61]:
x1 = init.uniform(torch.FloatTensor(3,4), a=0, b=9) # a에서 b사이의 값으로 초기화
x2 = init.normal(torch.FloatTensor(3,4), std=0.2) # 표준편차가 0.2 적용 초기화
x3 = init.constant(torch.FloatTensor(3,4), 3.145) # 지정된 상수값으로 초기화

x1, x2, x3

<ipython-input-61-3a46738e0000>:1: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  x1 = init.uniform(torch.FloatTensor(3,4), a=0, b=9) # a에서 b사이의 값으로 초기화
<ipython-input-61-3a46738e0000>:2: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  x2 = init.normal(torch.FloatTensor(3,4), std=0.2) # 표준편차가 0.2 적용 초기화
<ipython-input-61-3a46738e0000>:3: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  x3 = init.constant(torch.FloatTensor(3,4), 3.145) # 지정된 상수값으로 초기화


(tensor([[0.2089, 7.4604, 0.1894, 7.3652],
         [7.2142, 2.7827, 4.8648, 8.2510],
         [4.2807, 1.8686, 8.2181, 8.1188]]),
 tensor([[-0.0257,  0.1829,  0.1962, -0.1558],
         [ 0.0638,  0.0691, -0.5402,  0.1203],
         [ 0.1785,  0.2640,  0.2910, -0.0898]]),
 tensor([[3.1450, 3.1450, 3.1450, 3.1450],
         [3.1450, 3.1450, 3.1450, 3.1450],
         [3.1450, 3.1450, 3.1450, 3.1450]]))

# **4. Math Operations**
1) Arithmetic operations

In [62]:
# torch.add()
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1, x2)

x1, x2, add, x1 + x2, x1-x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [63]:
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.add(x1,10)

x1, x2, x1 + 10

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]))

In [64]:
# torch.mul() 곱하기
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)
x3, x1 * x2

(tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]))

In [65]:
# torch.div() 나누기
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.div(x1, 5)

x1, x2, x1 /5

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]),
 tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]))

# **2) Other Math Operations**

In [67]:
# torch.pow(input, exponent)
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])

x1, torch.pow(x1, 2), x1**2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]))

In [71]:
# torch.exp(tensor, out=None)
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
out = torch.exp(x1)

x1,out

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[  2.7183,   7.3891,  20.0855],
         [ 54.5981, 148.4132, 403.4288]]))

In [72]:
# torch.log(input, out=None) 자연로그 계산
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
out = torch.log(x1)

x1,out

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[0.0000, 0.6931, 1.0986],
         [1.3863, 1.6094, 1.7918]]))

# **3) Matrix opeation**

In [73]:
# torch.mm(mat1, mat2) --> matrix multiplication (행렬곱)
x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,5)
out = torch.mm(x1,x2)
x1, x2, out

(tensor([[ 4.0995e+37,  3.1692e-41,  4.0997e+37,  3.1692e-41],
         [ 1.1210e-43,  0.0000e+00,  8.9683e-44,  0.0000e+00],
         [-1.9584e+34,  3.1699e-41,  0.0000e+00,  0.0000e+00]]),
 tensor([[-1.2308e+30,  4.4044e-41,  1.6245e+34,  3.1692e-41,  4.4842e-44],
         [ 0.0000e+00,  1.5695e-43,  0.0000e+00, -3.2610e+37,  3.1699e-41],
         [ 6.1657e-44,  7.1466e-44,  1.3032e-43,  6.1657e-44,  1.2752e-43],
         [ 7.2868e-44,  6.1657e-44,  7.4269e-44,  6.1657e-44,  7.5670e-44]]),
 tensor([[       -inf,  1.8085e-03,         inf,  2.6825e-04,  7.0661e-06],
         [-1.3797e-13,  0.0000e+00,  1.8211e-09,  0.0000e+00,  0.0000e+00],
         [        inf, -8.6254e-07,        -inf, -1.0343e-03, -8.7816e-10]]))

In [74]:
# torch.bmm(batch1, batch2) --> batch 행렬곱 연산
# 맨 앞의 batch 는 차원을 유지하면서, 뒤 요소들의 행렬곱 연산함

x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.FloatTensor(10, 4, 5)
out = torch.bmm(x1, x2)

out.size()

torch.Size([10, 3, 5])

In [75]:
# torch.dot(tensor1, tensor2) : 벡터의 내적을 구함

x1 = torch.FloatTensor([1,2,3,4])
x2 = torch.FloatTensor([2,3,4,5])

torch.dot(x1, x2)

tensor(40.)

In [81]:
# torch.t(matrix) : transposed matrix (텐서의 전치 연산)
# 행과 열을 바꿈

x1 = torch.FloatTensor(3,4)

x1, x1.t()

(tensor([[ 4.1960e+37,  3.1692e-41, -1.2308e+30,  4.4044e-41],
         [ 8.9683e-44,  0.0000e+00,  1.1210e-43,  0.0000e+00],
         [-1.3694e+36,  3.1699e-41,  1.3593e-43,  0.0000e+00]]),
 tensor([[ 4.1960e+37,  8.9683e-44, -1.3694e+36],
         [ 3.1692e-41,  0.0000e+00,  3.1699e-41],
         [-1.2308e+30,  1.1210e-43,  1.3593e-43],
         [ 4.4044e-41,  0.0000e+00,  0.0000e+00]]))

In [86]:
# torch.transpose(input, dim_0, dim_1)
# 바꿀 차원을 2개 지정함
# 텐서의 내부 차원간 바꾸기

x1 = torch.FloatTensor(10, 3, 4)

# 1차원과 2차원을 서로 바꿈
x1.size(), torch.transpose(x1, 1, 2).size(), x1.transpose(1,2).size()

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [90]:
# torch.eig(input, eigenvectors=False)
# 고유값(eigen_value), 고유백터(eigen_vector) 반환
x1 = torch.FloatTensor(4,4)
x1, torch.linalg.eig(x1)

(tensor([[-1.2308e+30,  4.4044e-41,  4.1036e+37,  3.1692e-41],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  7.7052e+31,  7.2148e+22],
         [ 1.5766e-19,  1.0256e-08,  6.5631e-07,  3.1816e+12]]),
 torch.return_types.linalg_eig(
 eigenvalues=tensor([-1.2308e+30+0.j,  3.1816e+12+0.j,  7.7052e+31+0.j,  0.0000e+00+0.j]),
 eigenvectors=tensor([[ 1.0000e+00+0.j,  0.0000e+00+0.j,  1.0000e+00+0.j,  0.0000e+00+0.j],
         [ 0.0000e+00+0.j,  0.0000e+00+0.j,  0.0000e+00+0.j,  1.0000e+00+0.j],
         [ 0.0000e+00+0.j,  0.0000e+00+0.j,  1.9077e-06+0.j,  0.0000e+00+0.j],
         [ 0.0000e+00+0.j,  1.0000e+00+0.j,  1.6816e-44+0.j, -3.2235e-21+0.j]])))