# **1. import required libraries**

In [1]:
import torch
from torch.autograd import Variable

# **2. Tensor vs Variable**

**1) Declaration**

In [2]:
x_tensor = torch.Tensor(3,4)
x_tensor

tensor([[1.4729e+07, 4.4386e-41, 1.5362e+07, 4.4386e-41],
        [1.5362e+07, 4.4386e-41, 1.5362e+07, 4.4386e-41],
        [1.5362e+07, 4.4386e-41, 1.5362e+07, 4.4386e-41]])

In [3]:
x_variable = Variable(x_tensor)
x_variable

tensor([[1.4729e+07, 4.4386e-41, 1.5362e+07, 4.4386e-41],
        [1.5362e+07, 4.4386e-41, 1.5362e+07, 4.4386e-41],
        [1.5362e+07, 4.4386e-41, 1.5362e+07, 4.4386e-41]])

Variable 은 autogradient 가능함<br>
Pytorch 0.4 이상 버전에서는 Tensor에 Variable이 통합되고, Variable은
deprecated임.<br>Tensor만 사용

**2) Variable of a Variable**

In [4]:
# data 속성
x_variable.data

tensor([[1.4729e+07, 4.4386e-41, 1.5362e+07, 4.4386e-41],
        [1.5362e+07, 4.4386e-41, 1.5362e+07, 4.4386e-41],
        [1.5362e+07, 4.4386e-41, 1.5362e+07, 4.4386e-41]])

In [5]:
# grad 속성 : 값에 대한 gradient
# Variable 생성시 초기화되면서, gradient 도 같이 정의됨
print(x_variable.grad)

None


In [6]:
# requires_grad 속성 : 값에 대한 gradient 요구시 사용함
print(x_variable.requires_grad) # 속성의 설정값 확인 : False
# gradient 가 계산이 안된 상태임

False


In [9]:
# gradient 에 대한 연산을 수행하게 함 : True
x_variable = Variable(x_tensor, requires_grad=True)
x_variable.requires_grad

True

In [13]:
# volatile 속성 : 최소 메모리 사용에 대한 설정
# requires_grad 가 False이면, volatile 도 자동 False가 됨
x_variable = Variable(x_tensor, requires_grad = True)
x_variable.grad, x_variable.requires_grad, x_variable.volatile

<ipython-input-13-76461c3c011b>:4: UserWarning: volatile was removed (Variable.volatile is always False)
  x_variable.grad, x_variable.requires_grad, x_variable.volatile


(None, True, False)

# **3. Graph & Variables**

In [17]:
# create graph
x = Variable(torch.FloatTensor(3,4), requires_grad=True)
y = x**2 + 4*x
z = 2*y + 3

x.requires_grad, y.requires_grad, z.requires_grad

(True, True, True)

backword(gradient, retain_graph, create_graph, retain_variables)
현재 값 w, r, t, graph 에 대한 gradient 계산 함수임
역전파 알고리즘 적용된 계산함수임

In [19]:
# 위의 z 값으로 x의 gradient 를 계산해 냄
loss = torch.FloatTensor(3,4)
z.backward(loss)

print(x.grad)
y.grad, z.grad

tensor([[ 2.0223e+08,  3.5509e-40, -8.9486e+20,  2.4784e-40],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  5.6052e-44,  6.1642e+32,  5.7718e+23]])


<ipython-input-19-f26e95b4536c>:6: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  y.grad, z.grad


(None, None)